TaxReturnsApp/Controllers/AccountTransactionsController.cs
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using TaxReturns.DAL;
using TaxReturns.Models;
using TaxReturns.Helpers;
using System;
using System.Globalization;

namespace TaxReturns.Controllers
{
    public class AccountTransactionsController : Controller
    {
        private TaxReturnContext db = new TaxReturnContext();

        // GET: AccountTransactions
        public ActionResult Index(string filter)
        {
            IEnumerable<AccountTransaction> acs = db.accountTransactions.ToList();
            if (!string.IsNullOrEmpty(filter))
            {
                acs = acs.Where(x => x.Account.Contains(filter) || x.Description.Contains(filter));

            }
            return View(acs);
        }



        // GET: AccountTransactions/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            AccountTransaction accountTransaction = db.accountTransactions.Find(id);
            if (accountTransaction == null)
            {
                return HttpNotFound();
            }
            return View(accountTransaction);
        }

        // POST: AccountTransactions/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Account,Description,CurrencyCode,Amount")] AccountTransaction accountTransaction)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    var results = Utility.CultureInfoFromCurrencyISO(accountTransaction.CurrencyCode);
                    if (results.Count>0)
                    {
                        db.Entry(accountTransaction).State = EntityState.Modified;
                        db.SaveChanges();
                        return RedirectToAction("Index");
                    }
                    else
                    {
                        ModelState.AddModelError("", "Unable to save changes. Currency Code Not valid.");

                    }
                }
            }
            catch (DataException dex)
            {
                //Log the error (add a variable name after DataException)
              //  Elmah.ErrorSignal.FromCurrentContext().Raise(dex);
                ModelState.AddModelError("", "Unable to save changes. Try again, and if the problem persists see your system administrator.");
            }

            return View(accountTransaction);
        }

        // GET: AccountTransactions/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            AccountTransaction accountTransaction = db.accountTransactions.Find(id);
            if (accountTransaction == null)
            {
                return HttpNotFound();
            }
            return View(accountTransaction);
        }

        // POST: AccountTransactions/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            AccountTransaction accountTransaction = db.accountTransactions.Find(id);
            db.accountTransactions.Remove(accountTransaction);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        // GET: AccountTransactions/Create

        public ActionResult Create()
        {
            return View();
        }


        // POST: AccountTransactions/Create

        [HttpPost]
        [ActionName("Create")]
        public ActionResult Upload()
        {
            if (Request.Files["FileUpload1"].ContentLength > 0)
            {
                string extension = System.IO.Path.GetExtension(Request.Files["FileUpload1"].FileName).ToLower();

                HttpPostedFileBase postedFile = Request.Files["FileUpload1"];
                string postedFileName = Path.GetFileName(postedFile.FileName);

                string connString = "";

                string[] validFileTypes = { ".xls", ".xlsx", ".csv" };

                string path1 = string.Format("{0}/{1}", Server.MapPath("~/Content/Uploads"), postedFileName);
                if (!Directory.Exists(path1))
                {
                    Directory.CreateDirectory(Server.MapPath("~/Content/Uploads"));
                }
                if (validFileTypes.Contains(extension))
                {
                    // create errors data table
                    var errorsdt = new System.Data.DataTable("ErrorsDataTable");
                    errorsdt.Columns.Add("Account", typeof(string));
                    errorsdt.Columns.Add("Description", typeof(string));
                    errorsdt.Columns.Add("CurrencyCode", typeof(String));
                    errorsdt.Columns.Add("Amount", typeof(decimal));

                    if (System.IO.File.Exists(path1))
                    { System.IO.File.Delete(path1); }
                    Request.Files["FileUpload1"].SaveAs(path1);
                    if (extension == ".csv")
                    {
                        DataTable dt = Utility.ConvertCSVtoDataTable(path1);
                        InsertData(dt, errorsdt);

                    }
                    //Connection String to Excel Workbook  
                    //optional
                    else if (extension.Trim() == ".xls")
                    {
                        connString = "Provider=Microsoft.Jet.OLEDB.4.0;Data Source=" + path1 + ";Extended Properties=\"Excel 8.0;HDR=Yes;IMEX=2\"";
                        DataTable dt = Utility.ConvertXSLXtoDataTable(path1, connString);
                        InsertData(dt, errorsdt);
                    }
                    else if (extension.Trim() == ".xlsx")
                    {
                        connString = "Provider=Microsoft.ACE.OLEDB.12.0;Data Source=" + path1 + ";Extended Properties=\"Excel 12.0;HDR=Yes;IMEX=2\"";
                        DataTable dt = Utility.ConvertXSLXtoDataTable(path1, connString);
                        InsertData(dt, errorsdt);
                    }

                }
                else
                {
                    ViewBag.Error = "Please Upload Files in .xls, .xlsx or .csv format";

                }

            }

            return View();
        }

        private void InsertData(DataTable dt, DataTable errorsdt)
        {
            int count = 0;

            if (dt != null)
            {
                for (int i = 0; i < dt.Rows.Count; i++)
                {
                    AccountTransaction at = new AccountTransaction();

                    try
                    {
                        at.Account = dt.Rows[i]["Account"].ToString().Trim();
                        at.Description = dt.Rows[i]["Description"].ToString().Trim();
                        at.CurrencyCode = dt.Rows[i]["CurrencyCode"].ToString().Trim();
                        at.Amount = Convert.ToDecimal(dt.Rows[i]["Amount"].ToString().Trim());
                        if (ModelState.IsValid)
                        {
                            //Get currency symbol by currency code
                            var results = Utility.CultureInfoFromCurrencyISO(at.CurrencyCode);
                            if (results.Count > 0)
                            {
                                db.accountTransactions.Add(at);
                                count = count + 1;
                                db.SaveChanges();

                            }
                        }
                        else
                        {
                            // insert row values
                            errorsdt.Rows.Add(new Object[] { at.Account, at.Description, at.CurrencyCode, at.Amount });

                        }

                    }
                    catch (Exception e)
                    {
                        // insert row values
                        errorsdt.Rows.Add(new Object[] { at.Account, at.Description, at.CurrencyCode, at.Amount });


                    }
                }
                ViewBag.Data = errorsdt;
                if (count > 0)
                {
                    ViewBag.Count = count + " records inserted successfully!";
                }

            }
        }
        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

TaxReturnsApp/Views/AccountTransactions/Create.cshtml
@model TaxReturns.Models.AccountTransaction
@using System.Data;
@{
    ViewBag.Title = "Create Transaction";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="bs-header">
    <ul class="breadcrumb">
        <li>@Html.ActionLink("Home", "Index", "Home")</li>
        <li class="active">Create Transaction</></li>
    </ul>
</div>
<br />
<div class="panel panel-default panel-table">
    <div class="panel-heading">
        <strong>@ViewBag.Title</strong>
    </div>
    <div class="panel-body">
        @using (Html.BeginForm("Create", "AccountTransactions", FormMethod.Post, new { enctype = "multipart/form-data" }))

        {
            @Html.AntiForgeryToken()
            <div class="form-horizontal">
                <div class="form-group">
                    @Html.Label("Excel/CSV File", new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        <input type="file" id="FileUpload1" name="FileUpload1" />
                        <br />
                        <input type="submit" value="Upload" class="btn btn-success" />
                    </div>
                </div>

                <div class="form-horizontal">
                    @if (ViewBag.Count != null)
                    { @ViewBag.Count }
                    <hr />
                    <table id="">

                        @if (ViewBag.Data != null)
                        {
                            <thead>
                                 @foreach (DataColumn column in (ViewBag.Data as System.Data.DataTable).Columns)
                                {
                                <th>@column.ColumnName.ToUpper()</th>
                                }
                                </thead>
                            if ((ViewBag.Data as System.Data.DataTable).Rows.Count > 0)
                            {
                                foreach (DataRow dr in (ViewBag.Data as System.Data.DataTable).Rows)
                                {

                                    <tr>

                                        @foreach (DataColumn column in (ViewBag.Data as System.Data.DataTable).Columns)
                                        {
                                            <td data-title='@column.ColumnName'>

                                                @dr[column].ToString()
                                            </td>
                                        }

                                    </tr>

                                }
                                <tr><td>Please correct the above errors in the file and re upload..</td><td></td><td></td><td></td></tr>

                            }
                            else
                            {
                                int count = (ViewBag.Data as System.Data.DataTable).Columns.Count;
                                <tr>

                                    <td colspan='@count' style="color:red;">

                                        All records inserted successfully!!

                                    </td>
                                </tr>

                            }

                        }
                        else
                        {
                            if (ViewBag.Error != null)
                            {
                                <tr>
                                    <td style="color:red;">

                                        @(ViewBag.Error != null ? ViewBag.Error.ToString() : "")
                                    </td>
                                </tr>
                            }
                        }
                    </table>
                </div>
            </div>
        }

        <div>
            <br />    @Html.ActionLink((HttpUtility.HtmlDecode(" &laquo;") + " Back to List"), "Index", "AccountTransactions", null, new { @class = "btn btn-primary btn-large" })
        </div>

        @section Scripts {
            @Scripts.Render("~/bundles/jqueryval")
        }


    </div>
</div>

TaxReturnsApp/Views/AccountTransactions/Delete.cshtml
@model TaxReturns.Models.AccountTransaction

@{
    ViewBag.Title = "Delete AccountTransaction";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="bs-header">
    <ul class="breadcrumb">
        <li>@Html.ActionLink("Home", "Index", "Home")</li>
        <li class="active">Remove Transaction</></li>
    </ul>
</div>
<div class="panel panel-default panel-table">
    <div class="panel-heading">
        <strong>@ViewBag.Title</strong>
    </div>
    <div class="panel-body">
        <h3>Are you sure you want to delete this?</h3>
        <div>          
            <hr />
            <dl class="dl-horizontal">
                <dt>
                    @Html.DisplayNameFor(model => model.Account)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.Account)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.Description)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.Description)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.CurrencyCode)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.CurrencyCode)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.Amount)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.Amount)
                </dd>

            </dl>

            @using (Html.BeginForm())
            {
                @Html.AntiForgeryToken()

                <div class="form-actions no-color">
                    <input type="submit" value="Delete" class="btn btn-danger" /> |
                     @Html.ActionLink((HttpUtility.HtmlDecode(" &laquo;") + " Back to List"), "Index", "AccountTransactions", null, new { @class = "btn btn-primary btn-large" })
                </div>
            }
        </div>

    </div>
</div>

TaxReturnsApp/Views/AccountTransactions/Details.cshtml
@model TaxReturns.Models.AccountTransaction

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Details</h2>

<div>
    <h4>AccountTransaction</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Account)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Account)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CurrencyCode)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CurrencyCode)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Amount)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Amount)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

TaxReturnsApp/Views/AccountTransactions/Edit.cshtml
@model TaxReturns.Models.AccountTransaction

@{
    ViewBag.Title = "Edit Account Transaction";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="bs-header">
    <ul class="breadcrumb">
        <li>@Html.ActionLink("Home", "Index", "Home")</li>
        <li class="active">Edit Transaction</></li>
    </ul>
</div>
<br />
<div class="panel panel-default panel-table">
    <div class="panel-heading">
        <strong>@ViewBag.Title</strong>
    </div>
    <div class="panel-body">
        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()
            <div class="form-horizontal">
                <hr />
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                @Html.HiddenFor(model => model.Id)

                <div class="form-group">
                    @Html.LabelFor(model => model.Account, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Account, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Account, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.CurrencyCode, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.CurrencyCode, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.CurrencyCode, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Amount, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Amount, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Amount, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        <input type="submit" value="Save" class="btn btn-success" />
                    </div>
                </div>
            </div>
        }

        <div>
            @Html.ActionLink((HttpUtility.HtmlDecode(" &laquo;") + " Back to List"), "Index", "AccountTransactions", null, new { @class = "btn btn-primary btn-large" })
        </div>

        @section Scripts {
            @Scripts.Render("~/bundles/jqueryval")
        }


    </div>
</div>

TaxReturnsApp/Views/AccountTransactions/Index.cshtml
@model IEnumerable<TaxReturns.Models.AccountTransaction>
@using TaxReturns.Helpers
@{
    ViewBag.Title = "Account Transactions";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="bs-header">
    <ul class="breadcrumb">
        <li>@Html.ActionLink("Home", "Index", "Home")</li>
        <li class="active">Account Transactions</></li>
    </ul>
</div>

@using (Html.BeginForm("Index", "AccountTransactions", FormMethod.Get, new { @class = "form-horizontal", role = "form" }))
{
    <div class="row">
        <div class="col-sm-8">
            <div class="input-group">
                <input type="text"
                       name="filter"
                       value="@ViewBag.filter"
                       class="form-control"
                       style="display: inline"
                       placeholder="Search by account and description" />
                <span class="input-group-btn">
                    <button class="btn btn-primary" type="submit">Go</button>
                </span>

            </div>
        </div>
        <div class="pull-right col-lg-1">
            <div class="pull-right">
                @Html.NoEncodeActionLink("<span class='glyphicon glyphicon-plus'></span>", "Add new Transaction", "Create", "AccountTransactions", routeValues: null, htmlAttributes: new { @class = "btn btn-primary" })
            </div>
        </div>
    </div>
}
<br />
<div class="panel panel-default panel-table">
    <div class="panel-heading">
        <strong>@ViewBag.Title</strong>
    </div>
    <div class="panel-body">
        @if (Model.Count() > 0)
        {
            <table class="table">
                <tr>
                    <th>
                        @Html.DisplayNameFor(model => model.Account)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.Description)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.CurrencyCode)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.Amount)
                    </th>
                 
                    <th>Action</th>
                </tr>

                @foreach (var item in Model)
                {
                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => item.Account)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Description)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.CurrencyCode)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Amount)
                        </td>
                        <td>
                            <div class="pull-right">
                                @Html.NoEncodeActionLink("<span class='glyphicon glyphicon-pencil'></span>", "Edit", "Edit", "AccountTransactions", routeValues: new { id = item.Id }, htmlAttributes: new { data_modal = "", @class = "btn btn-default" })
                                &nbsp;
                                @Html.NoEncodeActionLink("<span class='glyphicon glyphicon-trash'></span>", "Delete", "Delete", "AccountTransactions", routeValues: new { id = item.Id }, htmlAttributes: new { data_modal = "", @class = "btn btn-danger" })

                            </div>
                        </td>
                    </tr>
                }

            </table>
        }

        else
        {
            @: <div class="text-muted">&nbsp; Search result Not Found.</div>
}
    </div>
</div>